// GERADO AUTOMATICAMENTE — não editar à mão.
// Ocupação da Festa dos Sócios: lista do café (Hospedin 21/07/2026) cruzada
// com os contratos do pós-venda. acao: sobe | desce | mantem | semContrato.
class OcupacaoQuarto {
  final String ocupante;
  final String? tier;
  final int? pct;
  final bool atrasado;
  final String acao;
  final String? recomendada;
  final String confianca; // ok | fuzzy | sem
  final List<String> flags;
  const OcupacaoQuarto({required this.ocupante, this.tier, this.pct, required this.atrasado, required this.acao, this.recomendada, required this.confianca, this.flags = const []});
  bool get deveTrocar => acao == 'sobe' || acao == 'desce';
}

const Map<String, OcupacaoQuarto> ocupacaoFesta = {
  '101': OcupacaoQuarto(ocupante: 'Cassio Coutinho de O...', tier: null, pct: null, atrasado: false, acao: 'semContrato', recomendada: null, confianca: 'sem', flags: []),
  '105': OcupacaoQuarto(ocupante: '*Sergio Henrique More...', tier: 'prata', pct: 15, atrasado: true, acao: 'desce', recomendada: 'luxo', confianca: 'ok', flags: ['ATRASADO']),
  '102': OcupacaoQuarto(ocupante: '*HIROSHI SUGIYA', tier: 'bronze', pct: 100, atrasado: false, acao: 'sobe', recomendada: 'comfort', confianca: 'ok', flags: []),
  '103': OcupacaoQuarto(ocupante: '*JOSÉ DIONISIO JUNIOR', tier: 'prata', pct: 13, atrasado: false, acao: 'mantem', recomendada: 'luxo', confianca: 'ok', flags: []),
  '104': OcupacaoQuarto(ocupante: '*MARINALDO DA SILVA D...', tier: 'prata', pct: 21, atrasado: false, acao: 'sobe', recomendada: 'comfort', confianca: 'ok', flags: []),
  '106': OcupacaoQuarto(ocupante: '*José Rorigues Ferrei...', tier: null, pct: null, atrasado: false, acao: 'semContrato', recomendada: null, confianca: 'sem', flags: []),
  '107': OcupacaoQuarto(ocupante: '*ZILMEDSON DE ARAUJO...', tier: 'prata', pct: 12, atrasado: false, acao: 'mantem', recomendada: 'luxo', confianca: 'ok', flags: []),
  '108': OcupacaoQuarto(ocupante: '*Ronaldo Fernandes', tier: 'prata', pct: 47, atrasado: false, acao: 'sobe', recomendada: 'comfort', confianca: 'ok', flags: []),
  '109': OcupacaoQuarto(ocupante: '*RITA SIBELLY CAETANO...', tier: 'ouro', pct: 10, atrasado: true, acao: 'sobe', recomendada: 'comfort', confianca: 'ok', flags: ['ATRASADO']),
  '110': OcupacaoQuarto(ocupante: '*Djeane do Socorro Si...', tier: 'ouro', pct: 49, atrasado: true, acao: 'sobe', recomendada: 'comfort', confianca: 'ok', flags: ['ATRASADO']),
  '111': OcupacaoQuarto(ocupante: '*SECUNDINO DOS SANTOS...', tier: 'prata', pct: 28, atrasado: false, acao: 'sobe', recomendada: 'comfort', confianca: 'ok', flags: []),
  '112': OcupacaoQuarto(ocupante: '*HELIO MARANGONI ALVES', tier: 'prata', pct: 16, atrasado: false, acao: 'mantem', recomendada: 'luxo', confianca: 'ok', flags: []),
  '114': OcupacaoQuarto(ocupante: '*Vinicius Barbosa Mar...', tier: 'bronze', pct: 17, atrasado: false, acao: 'mantem', recomendada: 'luxo', confianca: 'ok', flags: []),
  '115': OcupacaoQuarto(ocupante: '*JULIO CESAR FONSECA', tier: 'prata', pct: 41, atrasado: false, acao: 'sobe', recomendada: 'comfort', confianca: 'ok', flags: []),
  '116': OcupacaoQuarto(ocupante: '*GRAZIELE KELLY DA SI...', tier: 'prata', pct: 8, atrasado: false, acao: 'mantem', recomendada: 'luxo', confianca: 'ok', flags: ['<9%']),
  '117': OcupacaoQuarto(ocupante: '*Juan Kempen', tier: 'prata', pct: 28, atrasado: false, acao: 'sobe', recomendada: 'comfort', confianca: 'fuzzy', flags: []),
  '71': OcupacaoQuarto(ocupante: '*DÉCIO DE SOUZA FELIX', tier: 'prata', pct: 100, atrasado: false, acao: 'sobe', recomendada: 'comfort', confianca: 'ok', flags: []),
  '72': OcupacaoQuarto(ocupante: '*ELAINE DURVAL SILVA...', tier: 'prata', pct: 26, atrasado: false, acao: 'sobe', recomendada: 'comfort', confianca: 'ok', flags: []),
  '73': OcupacaoQuarto(ocupante: 'RAFAEL DE FRANÇA LIRA', tier: null, pct: null, atrasado: false, acao: 'semContrato', recomendada: null, confianca: 'sem', flags: []),
  '201': OcupacaoQuarto(ocupante: '*DOUGLAS ORTIZ', tier: 'bronze', pct: 25, atrasado: false, acao: 'desce', recomendada: 'luxo', confianca: 'ok', flags: []),
  '202': OcupacaoQuarto(ocupante: '*GIULIANO MARCELO VARIS', tier: 'bronze', pct: 22, atrasado: true, acao: 'desce', recomendada: 'luxo', confianca: 'ok', flags: ['ATRASADO']),
  '203': OcupacaoQuarto(ocupante: '*ADILSON AFONSO TAVARES', tier: 'ouro', pct: 0, atrasado: false, acao: 'desce', recomendada: 'comfort', confianca: 'ok', flags: ['<9%', 'OURO<9% não deveria vir']),
  '204': OcupacaoQuarto(ocupante: '*ADILSON AFONSO TAVARES', tier: 'ouro', pct: 0, atrasado: false, acao: 'desce', recomendada: 'comfort', confianca: 'ok', flags: ['<9%', 'OURO<9% não deveria vir']),
  '205': OcupacaoQuarto(ocupante: '*DILSON KOSSOSKI', tier: 'prata', pct: 35, atrasado: false, acao: 'desce', recomendada: 'comfort', confianca: 'ok', flags: []),
  '206': OcupacaoQuarto(ocupante: 'Elizabeth Reis', tier: 'ouro', pct: 15, atrasado: false, acao: 'desce', recomendada: 'comfort', confianca: 'fuzzy', flags: []),
  '207': OcupacaoQuarto(ocupante: '*RENATO NEWTON RAMLOW', tier: 'prata', pct: 32, atrasado: true, acao: 'desce', recomendada: 'comfort', confianca: 'ok', flags: ['ATRASADO']),
  '208': OcupacaoQuarto(ocupante: '*Karoline Fernandes S...', tier: 'ouro', pct: 14, atrasado: true, acao: 'desce', recomendada: 'comfort', confianca: 'ok', flags: ['ATRASADO']),
  '209': OcupacaoQuarto(ocupante: '*Aparecida Batista da...', tier: null, pct: null, atrasado: false, acao: 'semContrato', recomendada: null, confianca: 'sem', flags: []),
  '210': OcupacaoQuarto(ocupante: '*FABIO PEREIRA DA SILVA', tier: 'bronze', pct: 5, atrasado: true, acao: 'desce', recomendada: 'luxo', confianca: 'ok', flags: ['<9%', 'ATRASADO']),
  '135': OcupacaoQuarto(ocupante: 'Hector Oscar Martinez', tier: null, pct: null, atrasado: false, acao: 'semContrato', recomendada: null, confianca: 'sem', flags: []),
  '143': OcupacaoQuarto(ocupante: 'Lucas Kotleski Carvalho', tier: null, pct: null, atrasado: false, acao: 'semContrato', recomendada: null, confianca: 'sem', flags: []),
  '301': OcupacaoQuarto(ocupante: '*Francimuller Furtado...', tier: 'ouro', pct: 28, atrasado: false, acao: 'mantem', recomendada: 'comfort', confianca: 'ok', flags: []),
  '302': OcupacaoQuarto(ocupante: 'ITAMAR CATRINACHO', tier: null, pct: null, atrasado: false, acao: 'semContrato', recomendada: null, confianca: 'sem', flags: []),
  '121': OcupacaoQuarto(ocupante: '*Anna Caroline Ferrei...', tier: 'ouro', pct: 12, atrasado: true, acao: 'mantem', recomendada: 'comfort', confianca: 'ok', flags: ['ATRASADO']),
  '122': OcupacaoQuarto(ocupante: 'Reginaldo Parnow Ennes', tier: 'ouro', pct: 18, atrasado: true, acao: 'mantem', recomendada: 'comfort', confianca: 'ok', flags: ['ATRASADO']),
  '123': OcupacaoQuarto(ocupante: '*Raphael Douglas Vieira', tier: 'ouro', pct: 16, atrasado: true, acao: 'mantem', recomendada: 'comfort', confianca: 'ok', flags: ['ATRASADO']),
  '124': OcupacaoQuarto(ocupante: 'George El-Khouri', tier: null, pct: null, atrasado: false, acao: 'semContrato', recomendada: null, confianca: 'sem', flags: []),
  '125': OcupacaoQuarto(ocupante: '*Melin Karla Nobrega', tier: null, pct: null, atrasado: false, acao: 'semContrato', recomendada: null, confianca: 'sem', flags: []),
  '126': OcupacaoQuarto(ocupante: '*MARCOS LUIZ RIBEIRO', tier: 'prata', pct: 5, atrasado: false, acao: 'desce', recomendada: 'luxo', confianca: 'ok', flags: ['<9%']),
  '127': OcupacaoQuarto(ocupante: '*ADELVAN MENESES COSTA', tier: 'prata', pct: 32, atrasado: false, acao: 'mantem', recomendada: 'comfort', confianca: 'ok', flags: []),
  '129': OcupacaoQuarto(ocupante: '*Marcelo Tedesco da R...', tier: null, pct: null, atrasado: false, acao: 'semContrato', recomendada: null, confianca: 'sem', flags: []),
  '131': OcupacaoQuarto(ocupante: '*HARLEY MENEZES MORAE...', tier: 'ouro', pct: 0, atrasado: false, acao: 'mantem', recomendada: 'comfort', confianca: 'ok', flags: ['<9%', 'OURO<9% não deveria vir']),
  '132': OcupacaoQuarto(ocupante: '*FABRICIO APARECIDO S...', tier: 'ouro', pct: 40, atrasado: false, acao: 'mantem', recomendada: 'comfort', confianca: 'ok', flags: []),
  '133': OcupacaoQuarto(ocupante: '*Paulo Porto de Carva...', tier: 'prata', pct: 9, atrasado: true, acao: 'desce', recomendada: 'luxo', confianca: 'ok', flags: ['ATRASADO']),
  '134': OcupacaoQuarto(ocupante: '*GERALDO QUEIROZ TOSC...', tier: 'ouro', pct: 26, atrasado: false, acao: 'mantem', recomendada: 'comfort', confianca: 'ok', flags: []),
  '136': OcupacaoQuarto(ocupante: '*Renato Vital', tier: 'prata', pct: 22, atrasado: true, acao: 'mantem', recomendada: 'comfort', confianca: 'ok', flags: ['ATRASADO']),
  '137': OcupacaoQuarto(ocupante: '*SILVIO GABRIEL FREIRE', tier: 'prata', pct: 15, atrasado: false, acao: 'desce', recomendada: 'luxo', confianca: 'ok', flags: []),
  '138': OcupacaoQuarto(ocupante: '*MARCIO RODRIGUES CER...', tier: 'bronze', pct: 16, atrasado: false, acao: 'desce', recomendada: 'luxo', confianca: 'ok', flags: []),
  '139': OcupacaoQuarto(ocupante: '*LUCIANA LEAL', tier: 'prata', pct: 42, atrasado: true, acao: 'mantem', recomendada: 'comfort', confianca: 'ok', flags: ['ATRASADO']),
  '140': OcupacaoQuarto(ocupante: '*ALESSANDRO CARRER GODIM', tier: 'prata', pct: 25, atrasado: false, acao: 'mantem', recomendada: 'comfort', confianca: 'ok', flags: []),
  '141': OcupacaoQuarto(ocupante: '*SILVIO ATTILA LYRA A...', tier: 'ouro', pct: 33, atrasado: false, acao: 'mantem', recomendada: 'comfort', confianca: 'ok', flags: []),
  '142': OcupacaoQuarto(ocupante: '*ARTHUR CESAR TAVARES', tier: 'bronze', pct: 50, atrasado: false, acao: 'desce', recomendada: 'luxo', confianca: 'ok', flags: []),
  '144': OcupacaoQuarto(ocupante: '*GLEICY KELLY MARQUE...', tier: 'prata', pct: 23, atrasado: false, acao: 'desce', recomendada: 'comfort', confianca: 'ok', flags: []),
  '145': OcupacaoQuarto(ocupante: '*AIRTON MATRICARDI', tier: 'prata', pct: 26, atrasado: false, acao: 'mantem', recomendada: 'comfort', confianca: 'ok', flags: []),
  '146': OcupacaoQuarto(ocupante: '*SERGIO OLIVEIRA', tier: 'prata', pct: 10, atrasado: false, acao: 'desce', recomendada: 'luxo', confianca: 'fuzzy', flags: []),
  '147': OcupacaoQuarto(ocupante: '*JOSE ADINAN ORTOLAN', tier: 'bronze', pct: 20, atrasado: false, acao: 'desce', recomendada: 'luxo', confianca: 'ok', flags: []),
  '148': OcupacaoQuarto(ocupante: '*DANILO DOS SANTOS CA...', tier: 'bronze', pct: 23, atrasado: true, acao: 'desce', recomendada: 'luxo', confianca: 'ok', flags: ['ATRASADO']),
  '149': OcupacaoQuarto(ocupante: '*Renato Cosmo Garcia', tier: 'ouro', pct: 0, atrasado: true, acao: 'mantem', recomendada: 'comfort', confianca: 'ok', flags: ['<9%', 'OURO<9% não deveria vir', 'ATRASADO']),
  '150': OcupacaoQuarto(ocupante: '*CARMEM LUCIA RODRIGU...', tier: null, pct: null, atrasado: false, acao: 'semContrato', recomendada: null, confianca: 'sem', flags: []),
  '151': OcupacaoQuarto(ocupante: '*Victor Sbisa Bremer', tier: 'ouro', pct: 15, atrasado: false, acao: 'desce', recomendada: 'comfort', confianca: 'ok', flags: []),
  '153': OcupacaoQuarto(ocupante: '*JOSE DOMICIO DA SILVA', tier: 'ouro', pct: 11, atrasado: true, acao: 'mantem', recomendada: 'comfort', confianca: 'ok', flags: ['ATRASADO']),
  '154': OcupacaoQuarto(ocupante: '*Thiago de Lima Araújo', tier: 'prata', pct: 100, atrasado: false, acao: 'mantem', recomendada: 'comfort', confianca: 'ok', flags: []),
  '155': OcupacaoQuarto(ocupante: '*CLAUDIO DANIEL ALBERTI', tier: 'bronze', pct: 23, atrasado: false, acao: 'desce', recomendada: 'luxo', confianca: 'ok', flags: []),
  '156': OcupacaoQuarto(ocupante: '*José Virgílio Lima', tier: 'prata', pct: 15, atrasado: false, acao: 'desce', recomendada: 'luxo', confianca: 'ok', flags: []),
  '157': OcupacaoQuarto(ocupante: '*Murillo Amorim da Silva', tier: 'prata', pct: 52, atrasado: true, acao: 'mantem', recomendada: 'comfort', confianca: 'ok', flags: ['ATRASADO']),
  '158': OcupacaoQuarto(ocupante: '*Mario Augusto Pacheco', tier: 'prata', pct: 100, atrasado: true, acao: 'mantem', recomendada: 'comfort', confianca: 'ok', flags: ['ATRASADO']),
  '159': OcupacaoQuarto(ocupante: '*CARLOS ROBERTO PAIXA...', tier: 'ouro', pct: 41, atrasado: false, acao: 'mantem', recomendada: 'comfort', confianca: 'ok', flags: []),
  '160': OcupacaoQuarto(ocupante: '*NILSON LUZ CANGUSSU', tier: 'bronze', pct: 13, atrasado: false, acao: 'desce', recomendada: 'luxo', confianca: 'ok', flags: []),
  '161': OcupacaoQuarto(ocupante: '*Estela Ribas Ferezin', tier: 'prata', pct: 23, atrasado: false, acao: 'mantem', recomendada: 'comfort', confianca: 'ok', flags: []),
  '162': OcupacaoQuarto(ocupante: '*Agnaldo Castro', tier: null, pct: null, atrasado: false, acao: 'semContrato', recomendada: null, confianca: 'sem', flags: []),
  '164': OcupacaoQuarto(ocupante: '*EUDES DOS SANTOS MENDES', tier: 'ouro', pct: 8, atrasado: false, acao: 'mantem', recomendada: 'comfort', confianca: 'ok', flags: ['<9%', 'OURO<9% não deveria vir']),
  '165': OcupacaoQuarto(ocupante: '*OZANEIDE CAVALCANTI...', tier: 'prata', pct: 37, atrasado: false, acao: 'mantem', recomendada: 'comfort', confianca: 'ok', flags: []),
  '166': OcupacaoQuarto(ocupante: '*RICARDO LOPES DANIEL', tier: 'ouro', pct: 29, atrasado: true, acao: 'mantem', recomendada: 'comfort', confianca: 'ok', flags: ['ATRASADO']),
  '167': OcupacaoQuarto(ocupante: '*GUTEMBERGUE DANTAS', tier: 'prata', pct: 13, atrasado: false, acao: 'desce', recomendada: 'luxo', confianca: 'fuzzy', flags: []),
  '168': OcupacaoQuarto(ocupante: 'Adriano cicero dos sa...', tier: 'prata', pct: 10, atrasado: false, acao: 'desce', recomendada: 'luxo', confianca: 'ok', flags: []),
  '169': OcupacaoQuarto(ocupante: '*Flavio Nusbaum', tier: null, pct: null, atrasado: false, acao: 'semContrato', recomendada: null, confianca: 'sem', flags: []),
  '170': OcupacaoQuarto(ocupante: '*Lenise Vargas Flores...', tier: 'prata', pct: 18, atrasado: false, acao: 'desce', recomendada: 'luxo', confianca: 'ok', flags: []),
  '51': OcupacaoQuarto(ocupante: '*LUCIANO ALASMAR', tier: 'integral', pct: 62, atrasado: true, acao: 'sobe', recomendada: 'suiteVillamor', confianca: 'ok', flags: ['ATRASADO']),
  '52': OcupacaoQuarto(ocupante: 'Bruno de Santa Inez T...', tier: null, pct: null, atrasado: false, acao: 'semContrato', recomendada: null, confianca: 'sem', flags: []),
  '53': OcupacaoQuarto(ocupante: '*VALERIA GOMES DA SILVA', tier: 'bronze', pct: 35, atrasado: true, acao: 'mantem', recomendada: 'luxo', confianca: 'ok', flags: ['ATRASADO']),
  '54': OcupacaoQuarto(ocupante: '*KELLY ALMEIDA DE SOU...', tier: null, pct: null, atrasado: false, acao: 'semContrato', recomendada: null, confianca: 'sem', flags: []),
  '55': OcupacaoQuarto(ocupante: '*CRISTINA DE ARRUDA C...', tier: 'prata', pct: 0, atrasado: false, acao: 'mantem', recomendada: 'luxo', confianca: 'ok', flags: ['<9%']),
  '56': OcupacaoQuarto(ocupante: '*GEOMARCIO BARROS TAV...', tier: 'bronze', pct: 15, atrasado: true, acao: 'mantem', recomendada: 'luxo', confianca: 'ok', flags: ['ATRASADO']),
  '57': OcupacaoQuarto(ocupante: '*Katia Aline de Oliveira', tier: 'prata', pct: 10, atrasado: false, acao: 'mantem', recomendada: 'luxo', confianca: 'ok', flags: []),
  '58': OcupacaoQuarto(ocupante: '*Alexandre Rocha Duarte', tier: 'prata', pct: 24, atrasado: false, acao: 'sobe', recomendada: 'comfort', confianca: 'ok', flags: []),
  '59': OcupacaoQuarto(ocupante: '*Maicel Anesio Titto', tier: 'prata', pct: 12, atrasado: false, acao: 'mantem', recomendada: 'luxo', confianca: 'ok', flags: []),
};
