// GERADO AUTOMATICAMENTE — não editar à mão.
// Mapa 2.0: ocupação dos quartos DEPOIS das trocas executadas.
class OcupacaoNova {
  final String ocupante, tier;
  final int? pct;
  final String? veioDe; // quarto de origem (quando a pessoa foi realocada)
  const OcupacaoNova({required this.ocupante, required this.tier, this.pct, this.veioDe});
}

const Map<String, OcupacaoNova> ocupacaoNova = {
  '51': OcupacaoNova(ocupante: '*DANILO DOS SANTOS CA...', tier: 'bronze', pct: 23, veioDe: '148'),
  '52': OcupacaoNova(ocupante: 'Bruno de Santa Inez T...', tier: '', pct: null, veioDe: null),
  '53': OcupacaoNova(ocupante: '*VALERIA GOMES DA SILVA', tier: 'bronze', pct: 35, veioDe: null),
  '54': OcupacaoNova(ocupante: '*KELLY ALMEIDA DE SOU...', tier: '', pct: null, veioDe: null),
  '55': OcupacaoNova(ocupante: '*CLAUDIO DANIEL ALBERTI', tier: 'bronze', pct: 23, veioDe: '155'),
  '56': OcupacaoNova(ocupante: '*GEOMARCIO BARROS TAV...', tier: 'bronze', pct: 15, veioDe: null),
  '57': OcupacaoNova(ocupante: '*Katia Aline de Oliveira', tier: 'prata', pct: 10, veioDe: null),
  '58': OcupacaoNova(ocupante: '*GIULIANO MARCELO VARIS', tier: 'bronze', pct: 22, veioDe: '202'),
  '59': OcupacaoNova(ocupante: '*Maicel Anesio Titto', tier: 'prata', pct: 12, veioDe: null),
  '71': OcupacaoNova(ocupante: '*JOSE ADINAN ORTOLAN', tier: 'bronze', pct: 20, veioDe: '147'),
  '72': OcupacaoNova(ocupante: '*MARCIO RODRIGUES CER...', tier: 'bronze', pct: 16, veioDe: '138'),
  '73': OcupacaoNova(ocupante: 'RAFAEL DE FRANÇA LIRA', tier: '', pct: null, veioDe: null),
  '101': OcupacaoNova(ocupante: 'Cassio Coutinho de O...', tier: '', pct: null, veioDe: null),
  '102': OcupacaoNova(ocupante: '*Lenise Vargas Flores...', tier: 'prata', pct: 18, veioDe: '170'),
  '103': OcupacaoNova(ocupante: '*JOSÉ DIONISIO JUNIOR', tier: 'prata', pct: 13, veioDe: null),
  '104': OcupacaoNova(ocupante: '*Sergio Henrique More...', tier: 'prata', pct: 15, veioDe: '105'),
  '105': OcupacaoNova(ocupante: '*NILSON LUZ CANGUSSU', tier: 'bronze', pct: 13, veioDe: '160'),
  '106': OcupacaoNova(ocupante: '*José Rorigues Ferrei...', tier: '', pct: null, veioDe: null),
  '107': OcupacaoNova(ocupante: '*ZILMEDSON DE ARAUJO...', tier: 'prata', pct: 12, veioDe: null),
  '108': OcupacaoNova(ocupante: '*SILVIO GABRIEL FREIRE', tier: 'prata', pct: 15, veioDe: '137'),
  '109': OcupacaoNova(ocupante: '*José Virgílio Lima', tier: 'prata', pct: 15, veioDe: '156'),
  '110': OcupacaoNova(ocupante: '*GUTEMBERGUE DANTAS', tier: 'prata', pct: 13, veioDe: '167'),
  '111': OcupacaoNova(ocupante: '*SERGIO OLIVEIRA', tier: 'prata', pct: 10, veioDe: '146'),
  '112': OcupacaoNova(ocupante: '*HELIO MARANGONI ALVES', tier: 'prata', pct: 16, veioDe: null),
  '114': OcupacaoNova(ocupante: '*Vinicius Barbosa Mar...', tier: 'bronze', pct: 17, veioDe: null),
  '115': OcupacaoNova(ocupante: '*Paulo Porto de Carva...', tier: 'prata', pct: 9, veioDe: '133'),
  '116': OcupacaoNova(ocupante: '*ARTHUR CESAR TAVARES', tier: 'bronze', pct: 50, veioDe: '142'),
  '117': OcupacaoNova(ocupante: '*DOUGLAS ORTIZ', tier: 'bronze', pct: 25, veioDe: '201'),
  '121': OcupacaoNova(ocupante: '*Anna Caroline Ferrei...', tier: 'ouro', pct: 12, veioDe: null),
  '122': OcupacaoNova(ocupante: 'Reginaldo Parnow Ennes', tier: 'ouro', pct: 18, veioDe: null),
  '123': OcupacaoNova(ocupante: '*Raphael Douglas Vieira', tier: 'ouro', pct: 16, veioDe: null),
  '124': OcupacaoNova(ocupante: 'George El-Khouri', tier: '', pct: null, veioDe: null),
  '125': OcupacaoNova(ocupante: '*Melin Karla Nobrega', tier: '', pct: null, veioDe: null),
  '126': OcupacaoNova(ocupante: '*Djeane do Socorro Si...', tier: 'ouro', pct: 49, veioDe: '110'),
  '127': OcupacaoNova(ocupante: '*ADELVAN MENESES COSTA', tier: 'prata', pct: 32, veioDe: null),
  '129': OcupacaoNova(ocupante: '*Marcelo Tedesco da R...', tier: '', pct: null, veioDe: null),
  '131': OcupacaoNova(ocupante: '*Victor Sbisa Bremer', tier: 'ouro', pct: 15, veioDe: '151'),
  '132': OcupacaoNova(ocupante: '*FABRICIO APARECIDO S...', tier: 'ouro', pct: 40, veioDe: null),
  '133': OcupacaoNova(ocupante: '*Karoline Fernandes S...', tier: 'ouro', pct: 14, veioDe: '208'),
  '134': OcupacaoNova(ocupante: '*GERALDO QUEIROZ TOSC...', tier: 'ouro', pct: 26, veioDe: null),
  '135': OcupacaoNova(ocupante: 'Hector Oscar Martinez', tier: '', pct: null, veioDe: null),
  '136': OcupacaoNova(ocupante: '*Renato Vital', tier: 'prata', pct: 22, veioDe: null),
  '137': OcupacaoNova(ocupante: '*RITA SIBELLY CAETANO...', tier: 'ouro', pct: 10, veioDe: '109'),
  '138': OcupacaoNova(ocupante: '*DÉCIO DE SOUZA FELIX', tier: 'prata', pct: 100, veioDe: '71'),
  '139': OcupacaoNova(ocupante: '*LUCIANA LEAL', tier: 'prata', pct: 42, veioDe: null),
  '140': OcupacaoNova(ocupante: '*ALESSANDRO CARRER GODIM', tier: 'prata', pct: 25, veioDe: null),
  '141': OcupacaoNova(ocupante: '*SILVIO ATTILA LYRA A...', tier: 'ouro', pct: 33, veioDe: null),
  '142': OcupacaoNova(ocupante: '*Ronaldo Fernandes', tier: 'prata', pct: 47, veioDe: '108'),
  '143': OcupacaoNova(ocupante: 'Lucas Kotleski Carvalho', tier: '', pct: null, veioDe: null),
  '144': OcupacaoNova(ocupante: '*LUCIANO ALASMAR', tier: 'integral', pct: 62, veioDe: '51'),
  '145': OcupacaoNova(ocupante: '*AIRTON MATRICARDI', tier: 'prata', pct: 26, veioDe: null),
  '146': OcupacaoNova(ocupante: '*JULIO CESAR FONSECA', tier: 'prata', pct: 41, veioDe: '115'),
  '147': OcupacaoNova(ocupante: '*DILSON KOSSOSKI', tier: 'prata', pct: 35, veioDe: '205'),
  '148': OcupacaoNova(ocupante: '*RENATO NEWTON RAMLOW', tier: 'prata', pct: 32, veioDe: '207'),
  '149': OcupacaoNova(ocupante: '*SECUNDINO DOS SANTOS...', tier: 'prata', pct: 28, veioDe: '111'),
  '150': OcupacaoNova(ocupante: '*CARMEM LUCIA RODRIGU...', tier: '', pct: null, veioDe: null),
  '153': OcupacaoNova(ocupante: '*JOSE DOMICIO DA SILVA', tier: 'ouro', pct: 11, veioDe: null),
  '154': OcupacaoNova(ocupante: '*Thiago de Lima Araújo', tier: 'prata', pct: 100, veioDe: null),
  '155': OcupacaoNova(ocupante: '*Juan Kempen', tier: 'prata', pct: 28, veioDe: '117'),
  '156': OcupacaoNova(ocupante: '*ELAINE DURVAL SILVA...', tier: 'prata', pct: 26, veioDe: '72'),
  '157': OcupacaoNova(ocupante: '*Murillo Amorim da Silva', tier: 'prata', pct: 52, veioDe: null),
  '158': OcupacaoNova(ocupante: '*Mario Augusto Pacheco', tier: 'prata', pct: 100, veioDe: null),
  '159': OcupacaoNova(ocupante: '*CARLOS ROBERTO PAIXA...', tier: 'ouro', pct: 41, veioDe: null),
  '160': OcupacaoNova(ocupante: '*Alexandre Rocha Duarte', tier: 'prata', pct: 24, veioDe: '58'),
  '161': OcupacaoNova(ocupante: '*Estela Ribas Ferezin', tier: 'prata', pct: 23, veioDe: null),
  '162': OcupacaoNova(ocupante: '*Agnaldo Castro', tier: '', pct: null, veioDe: null),
  '164': OcupacaoNova(ocupante: '*GLEICY KELLY MARQUE...', tier: 'prata', pct: 23, veioDe: '144'),
  '165': OcupacaoNova(ocupante: '*OZANEIDE CAVALCANTI...', tier: 'prata', pct: 37, veioDe: null),
  '166': OcupacaoNova(ocupante: '*RICARDO LOPES DANIEL', tier: 'ouro', pct: 29, veioDe: null),
  '167': OcupacaoNova(ocupante: '*MARINALDO DA SILVA D...', tier: 'prata', pct: 21, veioDe: '104'),
  '168': OcupacaoNova(ocupante: 'Adriano cicero dos sa...', tier: 'prata', pct: 10, veioDe: null),
  '169': OcupacaoNova(ocupante: '*Flavio Nusbaum', tier: '', pct: null, veioDe: null),
  '170': OcupacaoNova(ocupante: '*HIROSHI SUGIYA', tier: 'bronze', pct: 100, veioDe: '102'),
  '206': OcupacaoNova(ocupante: 'Elizabeth Reis', tier: 'ouro', pct: 15, veioDe: null),
  '209': OcupacaoNova(ocupante: '*Aparecida Batista da...', tier: '', pct: null, veioDe: null),
  '301': OcupacaoNova(ocupante: '*Francimuller Furtado...', tier: 'ouro', pct: 28, veioDe: null),
  '302': OcupacaoNova(ocupante: 'ITAMAR CATRINACHO', tier: '', pct: null, veioDe: null),
};
