// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWsDC_91UQH3oxiKmXS2ewHpvLGzHV_H4',
    appId: '1:908967144787:web:8545a3e9caa9566bb485a6',
    messagingSenderId: '908967144787',
    projectId: 'crm-pessoal-d993d',
    authDomain: 'crm-pessoal-d993d.firebaseapp.com',
    storageBucket: 'crm-pessoal-d993d.firebasestorage.app',
    measurementId: 'G-547HW5234R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOg9qpDBN4UuAmJEl3SZdRsEGqeTcGlaw',
    appId: '1:908967144787:android:953d3e6ea4e41e40b485a6',
    messagingSenderId: '908967144787',
    projectId: 'crm-pessoal-d993d',
    storageBucket: 'crm-pessoal-d993d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6O6WPR2kWK3qP_yaS9eUablJeN7SkIZE',
    appId: '1:908967144787:ios:e4a259667de29d59b485a6',
    messagingSenderId: '908967144787',
    projectId: 'crm-pessoal-d993d',
    storageBucket: 'crm-pessoal-d993d.firebasestorage.app',
    iosBundleId: 'com.example.crmPessoal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6O6WPR2kWK3qP_yaS9eUablJeN7SkIZE',
    appId: '1:908967144787:ios:e4a259667de29d59b485a6',
    messagingSenderId: '908967144787',
    projectId: 'crm-pessoal-d993d',
    storageBucket: 'crm-pessoal-d993d.firebasestorage.app',
    iosBundleId: 'com.example.crmPessoal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWsDC_91UQH3oxiKmXS2ewHpvLGzHV_H4',
    appId: '1:908967144787:web:de96471237922669b485a6',
    messagingSenderId: '908967144787',
    projectId: 'crm-pessoal-d993d',
    authDomain: 'crm-pessoal-d993d.firebaseapp.com',
    storageBucket: 'crm-pessoal-d993d.firebasestorage.app',
    measurementId: 'G-VB0SZ2SPJX',
  );
}
